{
  lib,
  clan-core,
  #config,
  ...
}: let
  userData = import ../user-list.nix;
in {
  imports = [
    clan-core.clanModules.disk-id
  ];

  # DO NOT EDIT THIS FILE AFTER INSTALLATION of a machine
  # Otherwise your system might not boot because of missing partitions / filesystems
  # boot.loader.grub.efiSupport = lib.mkDefault true;
  boot.loader.systemd-boot.enable = true;
  # boot.loader.grub.efiInstallAsRemovable = lib.mkDefault true;
  disko.devices = {
    disk = {
      "main" = {
        # suffix is to prevent disk name collisions
        name = "main-"; # + suffix;
        type = "disk";
        # Set the following in flake.nix for each maschine:
        # device = <uuid>;

        content = {
          type = "gpt";
          partitions = {
            ESP = {
              size = "1G";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = ["umask=0077"];
              };
            };
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "zroot";
              };
            };
          };
        };
      };
    };
    zpool = {
      zroot = {
        type = "zpool";
        options.ashift = "12";

        datasets =
          {
            "local" = {
              type = "zfs_fs";
              mountpoint = "none";
            };

            "local/home" = {
              type = "zfs_fs";
              mountpoint = "/home";
              # any shared properties for the "home" dataset
            };

            "local/nix" = {
              type = "zfs_fs";
              mountpoint = "/nix";
              options."com.sun:auto-snapshot" = "false";
            };
            "local/root" = {
              type = "zfs_fs";
              mountpoint = "/";
              options."com.sun:auto-snapshot" = "false";
            };

            # 3) Then for each user, create a child dataset named local/home/<username>.
            #    Since parted-based disk config has no "children" block,
            #    we must define each as a separate entry in `datasets`.
          }
          # merges with the definitions above
          // lib.genAttrs
          (map (u: u.name) userData.users)
          (
            userName: let
              userSpec = lib.findFirst (u: u.name == userName) userData.users;
            in {
              # each attribute is named "local/home/alice", etc.
              name = "local/home/${userName}";

              type = "zfs_fs";
              mountpoint = "/home/${userName}";
              options = {
                refquota = "50G";
                compression = "lz4";
              };
            }
          );
      };
    };
  };
}
